-- view kunugan pasien
CREATE VIEW view_kunjungan_pasien as SELECT noRM,namapasien,kodeicdx,nama_penyakit,tgl_lahir,jenis_kelamin,tgl as tgl_kunjungan,jenis_kunjungan,tujuan_pelayanan,tujuan_pelayanan.kode_tupel,jenis_pasien.jenis_pasien as jenis_pasien,sumber_dana as kode_jenis FROM pasien JOIN kunjungan ON kunjungan.pasien_noRM = pasien.noRM join tujuan_pelayanan ON tujuan_pelayanan.kode_tupel=kunjungan.tupel_kode_tupel join periksa on periksa.kunjungan_no_urutkunjungan=kunjungan.no_urutkunjungan JOIN diagnosa on diagnosa.periksa_idperiksa=periksa.idperiksa join penyakit on penyakit.kodeicdx=diagnosa.kodesakit join jenis_pasien on kunjungan.sumber_dana=jenis_pasien.kode_jenis

CREATE view batch_pengadaan as CREATE view view_pengadaan as SELECT idobat,nama_obat,IFNULL(stok_awal,0) as status_stok_awal,SUM(detail_pembelian_obat.jumlah_satuan_kecil) as jumlah,DATE(tanggal) as tgl,tanggal_expired FROM obat JOIN detail_pembelian_obat ON detail_pembelian_obat.obat_idobat=obat.idobat GROUP BY idobat,status_stok_awal,tgl
CREATE view view_resep as SELECT idobat,nama_obat,DATE(tanggal) as tgl,SUM(jumlah_beri) as jumlah FROM obat JOIN detail_resep_diberikan ON detail_resep_diberikan.obat_idobat=obat.idobat GROUP BY idobat,tgl
CREATE view view_resep as SELECT idobat,nama_obat,DATE(tanggal) as tgl,SUM(jumlah_beri) as jumlah FROM obat JOIN detail_resep_diberikan ON detail_resep_diberikan.obat_idobat=obat.idobat GROUP BY idobat,tgl
CREATE view view_obat_rusak as SELECT obat.idobat,nama_obat,DATE(tanggal) as tgl,SUM(jumlah) as jumlah FROM obat JOIN obat_rusak ON obat_rusak.idobat=obat.idobat GROUP BY idobat,tgl

CREATE VIEW view_kunjungan as SELECT * FROM (SELECT DISTINCT kunjungan.*,IFNULL(tujuan_poli,kunjungan.tupel_kode_tupel) as poli_saat_ini,rujukan_internal.* FROM kunjungan LEFT JOIN rujukan_internal ON rujukan_internal.kunjungan_no_urutkunjungan=kunjungan.no_urutkunjungan) as data JOIN tujuan_pelayanan ON tujuan_pelayanan.kode_tupel=data.poli_saat_ini
